name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          KEY: ${{ secrets.KEY }}
          FINGERPRINT: ${{ secrets.FINGERPRINT }}
        run: |
          mkdir ${HOME}/.ssh
          printf "%s" "$KEY" > "${HOME}/.ssh/id_rsa"
          chmod 600 ${HOME}/.ssh/id_rsa
          printf "%s" "$FINGERPRINT" > "${HOME}/.ssh/known_hosts"
          chmod 600 ${HOME}/.ssh/known_hosts

      - name: Reload PM2 server
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
        run: |
          ssh ${USERNAME}@${HOST} -T << EOF
            cd ~/memebot/
            git fetch --all
            git reset --hard origin/master
            nvm install
            npm install --only=prod
            pm2 startOrReload ecosystem.config.cjs
            pm2 save
          EOF
